# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  emacs-ng = {
    pname = "emacs-ng";
    version = "b4bd1b8232a7d63690e48fc1946516265c9f2c83";
    src = fetchFromGitHub ({
      owner = "emacs-ng";
      repo = "emacs-ng";
      rev = "b4bd1b8232a7d63690e48fc1946516265c9f2c83";
      fetchSubmodules = true;
      sha256 = "sha256-wpWj9cvGcpWc24835Z4X5CZUKnn79jSCv49yJ1J3eVA=";
    });
  };
}
