# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  emacs-ng = {
    pname = "emacs-ng";
    version = "19de7340d4782268b8c9ac4138167d013ed3d834";
    src = fetchgit {
      url = "https://github.com/emacs-ng/emacs-ng";
      rev = "19de7340d4782268b8c9ac4138167d013ed3d834";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0ym5sh6d8fmqz36wihq98gyvilzldjsi99s6a3cv8p50011qxvzd";
    };
  };
}
