# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  emacs-ng = {
    pname = "emacs-ng";
    version = "93f38491a060f06ae4b85c8546b624a00e4750dc";
    src = fetchgit {
      url = "https://github.com/emacs-ng/emacs-ng";
      rev = "93f38491a060f06ae4b85c8546b624a00e4750dc";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "181gpfc4qlm9dcyj19gqhxlhrqnn9nqw5ypf6isv733dpb0gzf3v";
    };
  };
}
