site_name: Emacs NG - A new approach to Emacs
site_description: A new approach to Emacs - Including TypeScript, Threading, Async I/O, and WebRender.
site_url: https://emacs-ng.github.io/emacs-ng

repo_name: emacs-ng/emacs-ng
repo_url: https://github.com/emacs-ng/emacs-ng

nav:
  - Home:
    - Overview: README.md
    - Setup:
      - Build from source: building.md
      - Build with Docker: docker.md
      - Release .deb package: release.md
      - Nix Build / Develop: nix-develop.md
  - Deno/Javascript:
    - Using Deno: using-deno.md
    - Getting started: getting-started.md
    - Basic features: main-features.md
    - Advanced features: adv-features.md
    - Architecture: architecture.md
  - Webrender: webrender.md
  - Dynamic modules: ng-module.md
  - FAQ: faq.md
  - Native Hackers Handbook: handbook.md

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/emacs-ng/emacs-ng

extra_css:
  - stylesheets/layout.css

markdown_extensions:
  - pymdownx.superfences
  - codehilite
  - meta
  - toc:
      permalink: '#'
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized
