name: "CI"
on:
  pull_request:
  push:
jobs:
  nix-build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v14
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.5pre20211026_5667822/install

    # Configure Nix to enable flakes
    - run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf


    - name: Nix Flake Check
      run: nix -Lv flake check
    - name: Build emacsNg Rust Dependency
      # remove when nix build is fixed
      continue-on-error: true
      run: nix -Lv build .#emacsNg-rust

    - uses: cachix/cachix-action@v10
      with:
        name: emacsng
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

    - name: Run Emacsng Exec
      run: nix -Lv develop -c -- emacs --version
